# Generated by Django 6.0.3 on 2026-03-17 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Промокод"
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        help_text="Процент скидки от 1 до 100",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка (%)",
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Действует до")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        verbose_name="Максимальное количество использований"
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Использовано раз"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promocodes",
                        to="products.category",
                        verbose_name="Ограничение по категориям",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
                "ordering": ["code"],
            },
        ),
    ]
