# Generated by Django 6.0.3 on 2026-03-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="orders",
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table="order_items",
        ),
    ]
