# Generated by Django 6.0.3 on 2026-03-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
    ]
