# Generated by Django 6.0.3 on 2026-03-18 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_table_alter_product_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество единиц товара, доступных для заказа",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Остаток на складе",
            ),
        ),
    ]
